### ISSUE TITLE
Missing files in rgb_video file

### ISSUE THREAD

**Issue by icypear** [JWFanggit/LOTVS-CAP#13]
Hi, I just found the DADA-1000 dataset you provided, it seems like lack of 18, 19, 25, 35, 45, 48, 50 and 52 file in DADA-1000\testing\rgb_videos, so when I run Test.py, it always give me an Error of "TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>"

**Comment by Tranito** [comment]
How have you solved this issue?

**Comment by icypear** [comment]
just skip it

> How have you solved this issue?
