### ISSUE TITLE
unable to find the videos

### ISSUE THREAD

**Issue by RajArdeshna** [JWFanggit/LOTVS-CAP#2]
Hi,

I am impressed by the work you did and would like to try out your code with the instructions that you posted in README file.

However, I am not able to find the folders rgb_videos and focus_videos. Could you please help me with that?

Thanks in advance :)

**Comment by JWFanggit** [comment]
Hi, thank you for your interest in this work，you can download the DADA-1000 dataset via the link: [DADA-1000](Link：https://pan.baidu.com/s/1DrWdNm3u88naB-obGGrYDg 
code：rtg4). Then you can make the training and testing data structure of DADA-2000 based on the training.txt and tesiting.txt in Full-Train file.

**Comment by RajArdeshna** [comment]
Thanks for the reply. Also, I have another issue when i try to run Test.py script. I am trying to load the Mini_best_model.pth. However, i am getting an error saying missing some keys in the dictionary. Can you suggest me something to resolve that?

**Comment by JWFanggit** [comment]
Can you show me the error bug？

**Comment by RajArdeshna** [comment]
Okay i figured that bug out. It was due to the mismatch between the data used during the training and the model used for inference. 

I trained the model using the DADA-1000 data link that yousent me. I just used 2 training samples in training.txt and also trained it on 10 .jpg images. The training works fine and the model is getting saved.

However, when i try to run Test.py script with the model i got as an output in the previous step, i get the following error : 

![image](https://github.com/JWFanggit/LOTVS-CAP/assets/24778613/49a30119-da1b-48ac-971b-79da6e988c6b)


Is it because i just used 2 training samples in the training.txt file?

my training.txt looks somethig like this:

> 1/004 1 1 3 2,a pedestrian crosses the road
> 1/007 1 1 3 2,a person at blind spot
> 

I am just tring to get the whole chain running (training as well as testing). So, i am just using the dummy values in the training.txt

Once i get the whole chain running, i would go for a training with the full data.

Could you please give me some hints to solve this issue?

**Comment by JWFanggit** [comment]
maybe:  pred.cpu().detach().numpy.  It will be worked!

**Comment by RajArdeshna** [comment]
Unfortunately --> pred.cpu().detach().numpy. also does not work

**Comment by JWFanggit** [comment]
You need to make sure that the pred at each timestep has the shape (batch, 2).

**Comment by RajArdeshna** [comment]
Could you please provide some tips to ensure this ?
_You need to make sure that the pred at each timestep has the shape (batch, 2)._

**Comment by JWFanggit** [comment]
![11](https://github.com/JWFanggit/LOTVS-CAP/assets/83571975/6d316640-474e-4ac2-a500-ed762c913af5)
Referring to my result, you can check your output☺

**Comment by RajArdeshna** [comment]
Thanks a lot! I will give it a try :)

**Comment by RajArdeshna** [comment]
I am currently trying to tun the test. py script with the 'Min_best_model.pth' and [DADA-1000](Link：https://pan.baidu.com/s/1DrWdNm3u88naB-obGGrYDg.

However, i am getting the following error : 

![image](https://github.com/JWFanggit/LOTVS-CAP/assets/24778613/7ceecdc6-6e27-4fc1-b0ee-5497b999f3f0)

I am not sure how to proceed with this. Can you please help?

**Comment by JWFanggit** [comment]
I'm very sorry, this may be my code symbol error, you can change downsampling to upwnsampling and load the weights file again. Our code will be updated later when we make the dataset public.

**Comment by JWFanggit** [comment]
I'm very sorry, this may be my code symbol error, you can change downsampling to upsampling and load the weights file again. Our code will be updated later when we make the dataset public.

**Comment by RajArdeshna** [comment]
Thanks a lot for the information. Just to make sure i understood correctly, i have to change variable in the .pth file right?
Never did that so far. can you give me some hints on how can i do that?

**Comment by JWFanggit** [comment]
Hi. You don't need to change the weights file, just change downsampling to upsampling in the code and the weights file will load properly! 
![222](https://github.com/JWFanggit/LOTVS-CAP/assets/83571975/52c52fae-1cf5-4bc9-98ff-c74e72796ef9)

**Comment by RajArdeshna** [comment]
That works but i guess i also need to modify some things in order to get rid of the follow error :

```
RuntimeError: Error(s) in loading state_dict for accident:
        Unexpected key(s) in state_dict: "text.textNet.model.embeddings.position_ids", "fusion.text_model.model.embeddings.position_ids". 
```

Could you help me with this? I tried commenting some lines in the code but that did not help me.

**Comment by JWFanggit** [comment]
Hello. I think the key value (text.textNet.model) is not contained in our model, you have to check your code.

**Comment by JWFanggit** [comment]
Do you use wechat？ You can add me on WeChat for a better solution to your query.

**Comment by RajArdeshna** [comment]
sure, you can send me your id on rajardeshna619@gmail.com
