### ISSUE TITLE
Problems when run test.py

### ISSUE THREAD

**Issue by syf66888** [JWFanggit/LOTVS-CAP#8]
You have done a great job, congratulations. But it seems that there is a problem with the test.py you provided. After I changed the downsampling to upsampling, and use model.load_state_dict(weight,strict=False) loaded the pre-trained model you provided and ran test.py. The print "pred" is {'total_loss': tensor(287.2326 , device='cuda:0')} and subsequent testing cannot be performed.

**Comment by syf66888** [comment]
the problem above i have solved but i have another problem when running test.py, the auc cannot be calculated as below
![屏幕截图 2024-10-17 181306](https://github.com/user-attachments/assets/d54b5121-fda6-43ce-9f95-499cc3157200)

**Comment by syf66888** [comment]
I fixed the issue and it seems that I was using the text message incorrectly, so I closed this issue

**Comment by Tranito** [comment]
How did you solve the second issue of the ROC-AUC exactly?

**Comment by Tranito** [comment]
Can you explain what you mean with that you were using the text message incorrectly? I am wondering how you have solved it.

From my side, when inspecting the all_preds and the all_toas lists, I saw that for some videos the toa was 151 (see image below), which is higher than the amount of frames in one test video (150). Therefore I got the same error as you did.

![image](https://github.com/user-attachments/assets/900bdce9-955e-4f80-bbad-bafbb5cf8c11)

**Comment by syf66888** [comment]
I modified the txt file of the dataset, deleted the missing rgb file, and adjusted all the frames to 150, I hope it helps you

**Comment by Tranito** [comment]
Is it possible for you to send the changed txt files? I am wondering how you have changed those files.

**Comment by Tranito** [comment]
Which RGB file was missing for you exactly?
